SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
-- 예제
-- 1. Sales 부서 소속 사원의 이름과 입사일을 출력하라.
SELECT E.FIRST_NAME, E.HIRE_DATE FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE UPPER(D.DEPARTMENT_NAME) = UPPER('SALES');
-- 2. 커미션을 받는 직원의 이름과 그가 속한 부서명을 출력하라.
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.COMMISSION_PCT IS NOT NULL;

-- 3. Guy과 동일한 부서에서 근무하는 직원의 이름과 부서번호를 출력하라.
SELECT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE FIRST_NAME = 'Guy');


---------------------------------------------------------------------------

-- 1. 학과 테이블을 생성한다
CREATE TABLE SUBJECT (
    NO NUMBER GENERATED ALWAYS AS IDENTITY,
    S_NUM VARCHAR2(2) NOT NULL,
    S_NAME VARCHAR2(30) NOT NULL
);

ALTER TABLE SUBJECT ADD CONSTRAINT SUBJECT_PK PRIMARY KEY (NO);
ALTER TABLE SUBJECT ADD CONSTRAINT SUBJECT_UK UNIQUE (S_NUM);


INSERT INTO SUBJECT(S_NUM, S_NAME) VALUES('01', '컴퓨터학과');
INSERT INTO SUBJECT(S_NUM, S_NAME) VALUES('02', '교육학과');
INSERT INTO SUBJECT(S_NUM, S_NAME) VALUES('03', '신문방송학과');
INSERT INTO SUBJECT(S_NUM, S_NAME) VALUES('04', '인터넷비즈니스과');
INSERT INTO SUBJECT(S_NUM, S_NAME) VALUES('05', '기술경영과');

SELECT * FROM SUBJECT;
TRUNCATE TABLE SUBJECT;
ALTER TABLE SUBJECT MODIFY(NO GENERATED AS IDENTITY (START WITH 1));

--2. 학생 테이블을 생성한다
CREATE TABLE STUDENT (
    NO NUMBER(4) GENERATED ALWAYS AS IDENTITY,
    SD_NUM CHAR(8) NOT NULL,
    SD_NAME VARCHAR2(10) NOT NULL,
    SD_ID VARCHAR2(20) NOT NULL,
    SD_PASSWD VARCHAR2(30) NOT NULL,
    S_NUM VARCHAR2(2) NOT NULL,
    SD_JUMIN VARCHAR2(20) NOT NULL,
    SD_PHONE CHAR(11) NOT NULL,
    SD_ADDRESS VARCHAR2(100) NOT NULL,
    SD_EMAIL VARCHAR2(50) NOT NULL,
    SD_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY (NO);
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_UK UNIQUE (SD_NUM);
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_SUBJECT_FK FOREIGN KEY (S_NUM) REFERENCES SUBJECT(S_NUM); 



-- 3. 과목테이블을 생성한다. (LESSON)
CREATE TABLE LESSON (
    NO NUMBER GENERATED ALWAYS AS IDENTITY,
    L_NUM VARCHAR2(2) NOT NULL,
    L_NAME VARCHAR2(30) NOT NULL
);
ALTER TABLE LESSON ADD CONSTRAINT LESSON_PK PRIMARY KEY (NO);
ALTER TABLE LESSON ADD CONSTRAINT LESSON_UK UNIQUE (L_NUM);

-- 4. 수강 테이블을 생성한다(TRAINEE)
CREATE TABLE TRAINEE (
    NO NUMBER GENERATED ALWAYS AS IDENTITY,
    SD_NUM CHAR(8) NOT NULL,
    L_NUM VARCHAR2(2) NOT NULL,
    T_SECTION VARCHAR2(20) NOT NULL,
    T_DATE DATE DEFAULT SYSDATE
);
ALTER TABLE TRAINEE ADD CONSTRAINT TRAINEE_PK PRIMARY KEY (NO);

ALTER TABLE TRAINEE ADD CONSTRAINT TRAINEE_STUDENT_FK FOREIGN KEY (SD_NUM) REFERENCES STUDENT (SD_NUM);
ALTER TABLE TRAINEE ADD CONSTRAINT TRAINEE_LESSON_FK FOREIGN KEY (L_NUM) REFERENCES LESSON (L_NUM);


SELECT * FROM SUBJECT;
SELECT * FROM STUDENT;
SELECT * FROM LESSON;
SELECT * FROM TRAINEE;


SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'SUBJECT';
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'STUDENT';

ALTER TABLE STUDENT DROP CONSTRAINT STUDENT_SUBJECT_FK;
DROP TABLE SUBJECT;



