--1. 사원 번호와 사원명과 부서명과 부서의 위치를 출력하는 뷰(VIEW_LOC)를 작성하라.
CREATE OR REPLACE VIEW VIEW_LOC
AS
SELECT EMPLOYEE_ID, DEPARTMENT_NAME, CITY FROM EMPLOYEES 
INNER JOIN DEPARTMENTS USING (DEPARTMENT_ID)
INNER JOIN LOCATIONS USING (LOCATION_ID);

SELECT * FROM VIEW_LOC;
--2. 30번 부서 소속 사원의 이름과 입사일과 부서명을 출력하는 뷰(VIEW_DEPT30)를 작성하라.
CREATE OR REPLACE VIEW VIEW_DEPT30
AS
SELECT FIRST_NAME, HIRE_DATE, DEPARTMENT_ID, DEPARTMENT_NAME FROM EMPLOYEES
INNER JOIN DEPARTMENTS USING(DEPARTMENT_ID) WHERE DEPARTMENT_ID = 30;

SELECT * FROM VIEW_DEPT30;
--3. 부서별 최대 급여 정보를 가지는 뷰(VIEW_DEPT_MAXSAL)를 생성하라.
CREATE OR REPLACE VIEW VIEW_DEPT_MAXSAL
AS
SELECT DEPARTMENT_NAME, MAX(SALARY) AS MAX_SAL FROM EMPLOYEES INNER JOIN DEPARTMENTS 
USING(DEPARTMENT_ID) GROUP BY DEPARTMENT_NAME;

SELECT * FROM VIEW_DEPT_MAXSAL;
--4. 급여를 많이 받는 순서대로 3명만 출력하는 뷰(VIEW_SAL_TOP3)와 인라인 뷰로 작성하라.
CREATE OR REPLACE VIEW VIEW_SAL_TOP3
AS
SELECT FIRST_NAME, SALARY FROM (SELECT * FROM EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM<=3;

--인라인 뷰
SELECT FIRST_NAME, SALARY FROM (SELECT * FROM EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM<=3;
SELECT * FROM (SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM<=3;

SELECT * FROM VIEW_SAL_TOP3;

