--[문제 1] EMPLOYEES 테이블에 등록된 총사원의 수와 급여의 합, 급여의 평균을 변수에 대입하여 출력하 여 보자.
DECLARE
    EMP_SIZE NUMBER;
    TOTAL_SALARY EMPLOYEES.SALARY%TYPE;
    AVG_SALARY EMPLOYEES.SALARY%TYPE;
BEGIN
    SELECT COUNT(*), SUM(SALARY), AVG(SALARY)
    INTO EMP_SIZE, TOTAL_SALARY, AVG_SALARY
    FROM EMPLOYEES;
    
    DBMS_OUTPUT.PUT_LINE('총사원의 수 : '||EMP_SIZE);
    DBMS_OUTPUT.PUT_LINE('급여의 합 : '||TOTAL_SALARY);
    DBMS_OUTPUT.PUT_LINE('급여의 평균 : '||AVG_SALARY);
END;
/
SELECT * FROM EMPLOYEES;
 SELECT *
    FROM EMPLOYEES INNER JOIN DEPARTMENTS USING(DEPARTMENT_ID)
    WHERE UPPER(FIRST_NAME) = 'CLARA';
--[문제 2] Clara 사원의 직무, 급여, 입사일자, 커미션, 부서명을 변수에 대입하여 출력하여 보자.
DECLARE
    CLARA_INFO EMPLOYEES%ROWTYPE;
    DEP_INFO DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    SELECT *
    INTO CLARA_INFO
    FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'CLARA';
    
    SELECT DEPARTMENT_NAME
    INTO DEP_INFO 
    FROM DEPARTMENTS
    WHERE DEPARTMENT_ID = CLARA_INFO.DEPARTMENT_ID;
    DBMS_OUTPUT.PUT_LINE('직무 : ' || CLARA_INFO.JOB_ID);
    DBMS_OUTPUT.PUT_LINE('급여 : ' || CLARA_INFO.SALARY);
    DBMS_OUTPUT.PUT_LINE('입사일자 : ' || CLARA_INFO.HIRE_DATE);
    DBMS_OUTPUT.PUT_LINE('커미션 : ' || CLARA_INFO.COMMISSION_PCT);
    DBMS_OUTPUT.PUT_LINE('부서명 : ' || DEP_INFO);
END;
/