DROP TABLE REVIEW;

CREATE TABLE MOVIE(
    MOVIENUM NUMBER,
    MOVIENAME VARCHAR2(60) NOT NULL,
    RELEASEDATE DATE NOT NULL,
    RESERVATIONCOUNT NUMBER
);

ALTER TABLE MOVIE ADD CONSTRAINT MOVIE_PK PRIMARY KEY (MOVIENUM);

CREATE SEQUENCE MOVIE_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM MOVIE;
---------------------------
CREATE TABLE RESERVATION(
    PHONENUM VARCHAR2(20),
    USERNAME VARCHAR2(15) NOT NULL,
    MOVIENAME VARCHAR2(60) NOT NULL,
    SEATNUM NUMBER NOT NULL
);

ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_PK PRIMARY KEY (PHONENUM);
---------------------------
DROP TABLE REVIEW;
CREATE TABLE REVIEW(
    REVIEWNUM NUMBER,
    MOVIENAME VARCHAR2(60) NOT NULL,
    REVIEWRATE NUMBER(2,1) NOT NULL,
    REVIEW_CONTENT VARCHAR2(300) NOT NULL
);

ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_PK PRIMARY KEY (REVIEWNUM);

CREATE SEQUENCE REVIEW_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM REVIEW;

-------------------------------------------------------------------------
SELECT * FROM MOVIE;

INSERT INTO MOVIE VALUES (MOVIE_SEQ.NEXTVAL,'괴물','2006-07-27',0);
UPDATE MOVIE SET MOVIENAME = '극한직업', RELEASEDATE = '2019-01-23' WHERE MOVIENUM = '2';
DELETE FROM MOVIE WHERE MOVIENUM = '';

SELECT * FROM MOVIE WHERE MOVIENAME = '';

SELECT * FROM RESERVATION;
INSERT INTO RESERVATION VALUES ('010-1111-1111', '홍길동', '괴물', 10);
UPDATE RESERVATION SET PHONENUM = '010-2222-2222', USERNAME='저길동', MOVIENAME = '괴물', SEATNUM = '15' WHERE PHONENUM = '010-1111-1111';
DELETE FROM RESERVATION WHERE PHONENUM = '010-2222-2222';

SELECT * FROM REVIEW;
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, '괴물', 3.4, '역대급 액션!');
UPDATE REVIEW SET MOVIENAME = '괴물', REVIEWRATE = 3.6, REVIEW_CONTENT = '몰입도 최고에요!' WHERE REVIEWNUM = 3;
DELETE FROM REVIEW WHERE REVIEWNUM = 1;


-- 1. 현재 값 확인
SELECT REVIEW_SEQ.CURRVAL FROM DUAL;
-- 2. -(현재 값)으로 증감 값 변경
ALTER SEQUENCE REVIEW_SEQ INCREMENT BY -50;
-- 3. 변경 값 적용
SELECT REVIEW_SEQ.NEXTVAL FROM DUAL;
-- 4. 기존 값으로 증감 값 변경
ALTER SEQUENCE REVIEW_SEQ INCREMENT BY 1;
-- 5. 1번 값을 직접 삽입
CREATE TABLE REVIEW(NUM NUMBER);
INSERT INTO REVIEW(NUM) VALUES(1);
-- 6. 이 후 nextval을 이용해 넘버링
INSERT INTO TEST(NUM) VALUES(REVIEW_SEQ.NEXTVALUE);

SELECT MOVIENUM, MOVIENAME, TO_CHAR(RELEASEDATE, 'YYYY-MM-DD') RELEASEDATE, RESERVATIONCOUNT FROM MOVIE;
UPDATE MOVIE SET RESERVATIONCOUNT = 0 WHERE MOVIENUM = 21;
UPDATE MOVIE SET RESERVATIONCOUNT = 0 WHERE MOVIENUM = 23;
SELECT * FROM MOVIE;
COMMIT;




