DROP TABLE REVIEW;

CREATE TABLE MOVIE(
    MOVIENUM NUMBER,
    MOVIENAME VARCHAR2(60) NOT NULL,
    RELEASEDATE DATE NOT NULL,
    RESERVATIONCOUNT NUMBER
);

ALTER TABLE MOVIE ADD CONSTRAINT MOVIE_PK PRIMARY KEY (MOVIENUM);

CREATE SEQUENCE MOVIE_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM MOVIE;
---------------------------
CREATE TABLE RESERVATION(
    PHONENUM VARCHAR2(20),
    USERNAME VARCHAR2(15) NOT NULL,
    MOVIENAME VARCHAR2(60) NOT NULL,
    SEATNUM NUMBER NOT NULL
);

ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_PK PRIMARY KEY (PHONENUM);
---------------------------
DROP TABLE REVIEW;
CREATE TABLE REVIEW(
    REVIEWNUM NUMBER,
    MOVIENAME VARCHAR2(60) NOT NULL,
    REVIEWRATE NUMBER(2,1) NOT NULL,
    REVIEW_CONTENT VARCHAR2(300) NOT NULL
);

ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_PK PRIMARY KEY (REVIEWNUM);

CREATE SEQUENCE REVIEW_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM REVIEW;

-------------------------------------------------------------------------
SELECT * FROM MOVIE;
INSERT INTO MOVIE VALUES (MOVIE_SEQ.NEXTVAL,'괴물','2006-07-27',0);
UPDATE MOVIE SET MOVIENAME = '극한직업', RELEASEDATE = '2019-01-23' WHERE MOVIENUM = '2';
DELETE FROM MOVIE WHERE MOVIENUM = '';

SELECT * FROM MOVIE WHERE MOVIENAME = '';

SELECT * FROM RESERVATION;
INSERT INTO RESERVATION VALUES ('010-1111-1111', '홍길동', '괴물', 10);
UPDATE RESERVATION SET PHONENUM = '', USERNAME='', MOVIENAME = '', SEATNUM = '' WHERE MOVIENAME = '';

SELECT * FROM REVIEW;

