-- 2025.06.17 TESTADMIN
DROP TABLE MEMBER;
CREATE TABLE MEMBER (
    NO NUMBER,
    ID VARCHAR2(100) NOT NULL,
    PWD VARCHAR2(1000) NULL,
    NAME VARCHAR2(50) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE    
);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY (NO);

COMMIT;

CREATE SEQUENCE MEMBER_SEQ START WITH 1
INCREMENT BY 1;

SELECT * FROM ALL_SEQUENCES
WHERE SEQUENCE_NAME = 'MEMBER_SEQ';

---------------------------------------

SELECT * FROM MEMBER WHERE NO > 0 ORDER BY NO DESC, REG_DATE DESC;
SELECT * FROM MEMBER WHERE NO = 10000;
INSERT INTO MEMBER (NO, ID, PWD, NAME) VALUES (MEMBER_SEQ.NEXTVAL, 'ID', 'PWD', 'NAME');
UPDATE MEMBER SET ID='DI', PWD='DWP', NAME='EMAN' WHERE NO=10000;
DELETE FROM MEMBER WHERE NO=10000;

SELECT NO, ID, PWD, NAME, REG_DATE FROM MEMBER WHERE NO > 0 ORDER BY NO DESC, REG_DATE DESC;

SELECT * FROM MEMBER;




