-- MyBatis 관련 Board table
CREATE TABLE MYBATISBOARD( 
    NO NUMBER,
    TITLE VARCHAR2(100) NOT NULL, 
    CONTENT VARCHAR2(500) NULL, 
    WRITER VARCHAR2(50) NOT NULL, 
    REG_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE MYBATISBOARD ADD CONSTRAINT MYBATISBOARD_PK PRIMARY KEY (NO);

CREATE SEQUENCE MYBATISBOARD_SEQ
START WITH 1
INCREMENT BY 1;

select * from MYBATISBOARD;


-- MyBatis 관련 Board table
DROP TABLE MYBATISMEMBER;
CREATE TABLE MYBATISMEMBER (
    NO NUMBER,
    ID VARCHAR2(100) NOT NULL,
    PWD VARCHAR2(1000) NULL,
    NAME VARCHAR2(50) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE    
);

ALTER TABLE MYBATISMEMBER ADD CONSTRAINT MYBATISMEMBER_PK PRIMARY KEY (NO);

COMMIT;

CREATE SEQUENCE MYBATISMEMBER_SEQ START WITH 1
INCREMENT BY 1;

SELECT * FROM ALL_SEQUENCES
WHERE SEQUENCE_NAME = 'MYBATISMEMBER_SEQ';



