-- 회원관리 1, 회원권한 N
CREATE TABLE MYMEMBER( 
    NO NUMBER,
    ID VARCHAR2(50) NOT NULL, 
    PW VARCHAR2(50) NOT NULL, 
    NAME VARCHAR2(100) NOT NULL, 
    COIN NUMBER(10) DEFAULT 0,
    REG_DATE DATE DEFAULT SYSDATE, 
    UPD_DATE DATE DEFAULT SYSDATE, 
    ENABLED CHAR(1) DEFAULT '1'
);

ALTER TABLE MYMEMBER ADD CONSTRAINT MYMEMBER_PK PRIMARY KEY (NO);

CREATE SEQUENCE MYMEMBER_SEQ
START WITH 1
INCREMENT BY 1;

-- 회원권한 설정
CREATE TABLE MYMEMBER_AUTH( 
    NO NUMBER NOT NULL, 
    AUTH VARCHAR2(50) NOT NULL
);

ALTER TABLE MYMEMBER_AUTH ADD CONSTRAINT MYMEMBER_AUTH_NO_FK FOREIGN KEY(NO) 
REFERENCES MYMEMBER(NO);

-- 회원 이메일
CREATE TABLE MYMEMBER_EMAIL( 
    NO NUMBER NOT NULL, 
    EMAIL VARCHAR2(50) NOT NULL
);

ALTER TABLE MYMEMBER_EMAIL ADD CONSTRAINT MYMEMBER_EMAIL_NO_FK FOREIGN KEY(NO)
REFERENCES MYMEMBER(NO);

--------------------------------------

SELECT * FROM MYMEMBER;
SELECT * FROM MYMEMBER_AUTH;
SELECT * FROM MYMEMBER_EMAIL;

INSERT INTO MYMEMBER (NO, ID, PW, NAME) VALUES(MYMEMBER_SEQ.NEXTVAL, 'AAA', '1234', 'KDJ');
INSERT INTO MYMEMBER_AUTH (NO, AUTH) VALUES (1 , 'ADMIN');
INSERT INTO MYMEMBER_EMAIL (NO, EMAIL) VALUES (3, 'aaa@ccc.com');

SELECT MYMEMBER_SEQ.NEXTVAL FROM DUAL;

SELECT MM.NO,MM.ID, PW, NAME, REG_DATE, UPD_DATE, AUTH, EMAIL
FROM MYMEMBER MM 
LEFT OUTER JOIN MYMEMBER_AUTH A ON MM.NO= A.NO
LEFT OUTER JOIN MYMEMBER_EMAIL E ON MM.NO= E.NO
WHERE MM.NO = 3;

SELECT NO,ID, PW, NAME, REG_DATE
FROM MYMEMBER ORDER BY REG_DATE DESC;

UPDATE MYMEMBER SET NAME ='SSS' WHERE NO = 1;

DELETE FROM MYMEMBER WHERE NO = 1;

DELETE FROM MYMEMBER_AUTH WHERE NO = 1;

ROLLBACK;

